source 'https://rubygems.org'
gem 'rest-client'
gem 'telegram-bot-ruby'
gem 'nokogiri'
gem 'byebug'
gem 'mechanize'
gem 'json'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }


